Fix: prod container build and run (#2)
- fix: the follow error that was being thrown on startup by updating llama-index to 0.6.19
ref: https://github.com/jerryjliu/llama_index/issues/3858
raise TypeError("Instance and class checks can only be used with"
TypeError: Instance and class checks can only be used with @runtime_checkable protocols

- fix: dockerfile. switch base image from alpine to slim-buster. Plus some other tweaks

- fix: poe tasks in pyproject.toml to use slim-buster
- chore: add env-file support to docker-run task. update gitignore.
- docs: update to reflect changes
- CD: add docker publish action
  - Only Github Package Registry
  - Set to manual trigger.
- refactor: remove env var load function. 
it's not needed. Streamlit autobinds secrets.toml to env vars
if the file is present.

- docs: README.md typo Co-authored-by: Chen Wang <dev@chenwang.org>



---------

Co-authored-by: Chen Wang <dev@chenwang.org>